services:
    dico-db:
        image: mongo:6.0
        container_name: dico-mongodb
        environment:
            - MONGO_INITDB_DATABASE=dico-db
        ports:
            - "27027:27017"
    dico:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dico
        ports:
            - "4242:4242"
        depends_on:
            - dico-db
        environment:
            - MONGO_URI=mongodb://dico-db:27017/dico-db
            - MONGO_DB=dico-db
    populate:
        build:
            context: .
            dockerfile: Dockerfile.populate
        depends_on:
            - dico-db
        environment:
            - MONGO_URI=mongodb://dico-db:27017/dico-db
            - MONGO_DB=dico-db
        restart: "no"

    # Prometheus for metrics
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        restart: unless-stopped

    # Grafana for visualization
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        depends_on:
            - prometheus
            - loki
            - tempo

    # Loki for logs
    loki:
        image: grafana/loki:latest
        container_name: loki
        ports:
            - "3100:3100"
        volumes:
            - ./loki:/etc/loki
            - loki_data:/loki
        command: -config.file=/etc/loki/loki-config.yml
        restart: unless-stopped

    # Promtail to collect logs
    promtail:
        image: grafana/promtail:latest
        container_name: promtail
        volumes:
            - ./promtail:/etc/promtail
            - /var/log:/var/log
            - ./logs:/logs
        command: -config.file=/etc/promtail/promtail-config.yml
        depends_on:
            - loki
        restart: unless-stopped

    # Tempo for tracing
    tempo:
        image: grafana/tempo:latest
        container_name: tempo
        ports:
            - "14268:14268"  # Jaeger ingest
            - "3200:3200"    # Tempo
            - "9411:9411"    # Zipkin
        volumes:
            - ./tempo:/etc/tempo
            - ./tempo_data:/tmp/tempo
        command: -config.file=/etc/tempo/tempo-config.yml
        restart: unless-stopped

volumes:
    prometheus_data:
    grafana_data:
    loki_data:
    tempo_data: