services:
    dico-db:
        image: mongo:6.0
        container_name: dico-mongodb
        environment:
            - MONGO_INITDB_DATABASE=dico-db
        ports:
            - "27027:27017"
    dico:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dico
        ports:
            - "4242:4242"
        depends_on:
            - dico-db
        environment:
            - MONGO_URI=mongodb://dico-db:27017/dico-db
            - MONGO_DB=dico-db
    populate:
        build:
            context: .
            dockerfile: Dockerfile.populate
        depends_on:
            - dico-db
        environment:
            - MONGO_URI=mongodb://dico-db:27017/dico-db
            - MONGO_DB=dico-db
        restart: "no"